In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/income-classification/income_evaluation.csv

In [2]:
import seaborn as sns 
import matplotlib.pyplot as plt

df = pd.read_csv('/kaggle/input/income-classification/income_evaluation.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              32561 non-null  int64
 1    workclass       32561 non-null  object
 2    fnlwgt          32561 non-null  int64
 3    education       32561 non-null  object
 4    education-num   32561 non-null  int64
 5    marital-status  32561 non-null  object
 6    occupation      32561 non-null  object
 7    relationship    32561 non-null  object
 8    race            32561 non-null  object
 9    sex             32561 non-null  object
 10   capital-gain    32561 non-null  int64
 11   capital-loss    32561 non-null  int64
 12   hours-per-week  32561 non-null  int64
 13   native-country  32561 non-null  object
 14   income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
df.columns = df.columns.str.strip()
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [5]:
categorical = [col for col in df.columns if df[col].dtype == 'O']
numerical = [col for col in df.columns if df[col].dtype != 'O']

In [6]:
categorical

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native-country',
 'income']

In [7]:
for col in df.columns : 
    print('\n',df[col].value_counts())

 age
36    898
31    888
34    886
23    877
35    876
     ...
83      6
88      3
85      3
86      1
87      1
Name: count, Length: 73, dtype: int64

 workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

 fnlwgt
164190    13
203488    13
123011    13
148995    12
121124    12
          ..
232784     1
325573     1
140176     1
318264     1
257302     1
Name: count, Length: 21648, dtype: int64

 education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

 education-num
9     10501
10     7291
13     5355
14     1723
11     1382
7      1175
12     1067
6       933
4       646
15      576
5       514
8       433
16      413
3       333
2       168
1        51
Name: count, dtype: int64

 marital-status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

 occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

 relationship
Husband           13193
Not-in-family      8305
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

 race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

 sex
Male      21790
Female    10771
Name: count, dtype: int64

 capital-gain
0        29849
15024      347
7688       284
7298       246
99999      159
         ...
1111         1
2538         1
22040        1
4931         1
5060         1
Name: count, Length: 119, dtype: int64

 capital-loss
0       31042
1902      202
1977      168
1887      159
1848       51
        ...
2080        1
1539        1
1844        1
2489        1
1411        1
Name: count, Length: 92, dtype: int64

 hours-per-week
40    15217
50     2819
45     1824
60     1475
35     1297
      ...
82        1
92        1
87        1
74        1
94        1
Name: count, Length: 94, dtype: int64

 native-country
United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Laos                             18
Thailand                         18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

 income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [8]:
for col in ['workclass' , 'occupation' , 'native-country'] :
    df[col] = df[col].replace(' ?' , np.nan)

In [9]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop(columns = 'income' , axis = 1 )
y = df['income']
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 15)

In [11]:
X_train.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
32174,44,Self-emp-not-inc,157217,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0,0,42,United-States
2680,26,Local-gov,336969,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,28,El-Salvador
10874,53,Private,233369,Some-college,10,Widowed,Exec-managerial,Unmarried,White,Female,0,0,40,United-States
25028,30,Private,348618,9th,5,Married-civ-spouse,Craft-repair,Husband,Other,Male,0,0,40,Mexico
25881,50,Self-emp-inc,140516,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States

In [12]:
for col in ['workclass' , 'native-country' , 'occupation'] : 
    X_train[col] = X_train[col].fillna(X_train[col].mode()[0])
    X_test[col] = X_test[col].fillna(X_train[col].mode()[0])

In [13]:
X_test.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64

In [14]:
y_train = y_train.apply(lambda x : 1 if x.strip() == '>50K' else 0)

In [15]:
y_test = y_test.apply(lambda x : 1 if x.strip() == '>50K' else 0)

In [16]:
y_train.value_counts()

income
0    17276
1     5516
Name: count, dtype: int64

In [17]:
target_means = y_train.groupby(X_train['native-country']).mean()

for i in[X_train , X_test] : 
    i['native-country-encoded'] = i['native-country'].map(target_means)
    i['native-country-encoded'] = i['native-country-encoded'].fillna(y_train.mean())

In [18]:
X_train.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,native-country-encoded
32174,44,Self-emp-not-inc,157217,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0,0,42,United-States,0.247311
2680,26,Local-gov,336969,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,28,El-Salvador,0.129032
10874,53,Private,233369,Some-college,10,Widowed,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,0.247311
25028,30,Private,348618,9th,5,Married-civ-spouse,Craft-repair,Husband,Other,Male,0,0,40,Mexico,0.062907
25881,50,Self-emp-inc,140516,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,0.247311

In [19]:
for i in[X_train , X_test] : 
    i.drop(columns = 'native-country',axis = 1 , inplace = True )

In [20]:
one_hot_enc = ['workclass' , 'marital-status' , 'relationship' , 'race' , 'sex' , 'occupation']

X_train_enc = pd.get_dummies(data = X_train , columns = one_hot_enc , drop_first = True , dtype = int)
X_test_enc = pd.get_dummies(data = X_test , columns = one_hot_enc  , drop_first = True , dtype = int)

In [21]:
X_train_enc.head()

,age,fnlwgt,education,education-num,capital-gain,capital-loss,hours-per-week,native-country-encoded,workclass_ Local-gov,workclass_ Never-worked,...,occupation_ Farming-fishing,occupation_ Handlers-cleaners,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving
32174,44,157217,Bachelors,13,0,0,42,0.247311,0,0,...,0,0,0,0,0,0,0,1,0,0
2680,26,336969,Bachelors,13,0,0,28,0.129032,1,0,...,0,0,0,0,0,1,0,0,0,0
10874,53,233369,Some-college,10,0,0,40,0.247311,0,0,...,0,0,0,0,0,0,0,0,0,0
25028,30,348618,9th,5,0,0,40,0.062907,0,0,...,0,0,0,0,0,0,0,0,0,0
25881,50,140516,Bachelors,13,0,0,40,0.247311,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
# TRAIN

In [23]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

In [24]:
X_train_enc.drop(columns = 'education' , axis = 1 , inplace = True)
X_test_enc.drop(columns = 'education' , axis = 1 , inplace = True)

X_train = scaler.fit_transform(X_train_enc)
X_test = scaler.transform(X_test_enc)

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train , y_train)

RandomForestClassifier()

In [26]:
y_pred = rfc.predict(X_test)

from sklearn.metrics import accuracy_score , confusion_matrix , classification_report 

print('Accuracy : \n' , accuracy_score(y_test , y_pred))
print('Classification Report :  \n ' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))

Accuracy :
 0.8646739686764254
Classification Report :
                precision    recall  f1-score   support

           0       0.89      0.93      0.91      7444
           1       0.75      0.65      0.69      2325

    accuracy                           0.86      9769
   macro avg       0.82      0.79      0.80      9769
weighted avg       0.86      0.86      0.86      9769

Confusion Matrix :
 [[6944  500]
 [ 822 1503]]

In [27]:
# Hyperparamather Tuning :

In [28]:
from sklearn.model_selection import RandomizedSearchCV , StratifiedKFold
cv = StratifiedKFold(n_splits = 5)
params = {
    'n_estimators' : [100 , 300 , 600 , 1000],
    'max_depth' : [3 ,5 , 7 ,9 , 15 ,None],
    'criterion' : ['gini' , 'entropy' , 'log_loss'],
    'max_features' : ['sqrt' , 'log2' , None],
    'n_jobs' : [-1]
}

In [29]:
random = RandomizedSearchCV(estimator = RandomForestClassifier(class_weight = 'balanced') , param_distributions = params , scoring = 'accuracy' , cv = cv , n_jobs = -1 )
random.fit(X_train , y_train)
y_pred = random.predict(X_test)

print('Accuracy : \n' , accuracy_score(y_test , y_pred))
print('Classification Report :  \n ' , classification_report(y_test , y_pred))
print('Confusion Matrix : \n' , confusion_matrix(y_test , y_pred))

Accuracy :
 0.8599651960282526
Classification Report :
                precision    recall  f1-score   support

           0       0.89      0.93      0.91      7444
           1       0.74      0.64      0.69      2325

    accuracy                           0.86      9769
   macro avg       0.81      0.78      0.80      9769
weighted avg       0.86      0.86      0.86      9769

Confusion Matrix :
 [[6910  534]
 [ 834 1491]]